name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rgb-matrix-app:$(date +%Y%m%d) --tag rgb-matrix-app:latest
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/rgb-matrix-app:latest
        docker push ghcr.io/${{ github.repository_owner }}/rgb-matrix-app:$(date +%Y%m%d)